import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { getAll } from './cvAPI';
import { ICv } from '@virtual-me/virtual-me-ts-core';


export interface ICVState {
  list: ICv[]

}

const getInitialState: () => ICVState = () => {
  let state: ICVState = {
    list: []
  }
  return state;
};

export const getCvAsync = createAsyncThunk(
  'cv/all',
  async () => {
    const response = await getAll();
    return response.data;
  }
);

export const cvSlice = createSlice({
  name: 'cv',
  initialState: getInitialState(),
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    reset: () => getInitialState()
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getCvAsync.pending, (state, { meta }) => {
        return { ...state, status: 'loading' };
      })
      .addCase(getCvAsync.fulfilled, (state, action: PayloadAction<ICv[]>) => {
        state.list = action.payload;
        
        return state
      })
      .addCase(getCvAsync.rejected, (state, action: PayloadAction<any>) => {
        return { ...state, status: 'error', list: [] }
      });
  }
});

export const { reset } = cvSlice.actions;

//export const selectToken = (state: RootState) => state.auth.token;

export default cvSlice.reducer;
